-- BikeStores sample database (sqlservertutorial.net, © 2017; scripts mirrored at github.com/ant-analytics/mssql docs/), ported to PostgreSQL:
-- schemas production/sales flattened into public (no name clashes), IDENTITY -> integer (kept as GENERATED BY DEFAULT AS IDENTITY on customers and stores, whose ids the source assigns by insertion order), tinyint -> smallint, FK actions dropped; PK/FK/UNIQUE/NOT NULL/DEFAULT preserved.
CREATE TABLE categories (
	category_id integer PRIMARY KEY,
	category_name varchar(255) NOT NULL
);

CREATE TABLE brands (
	brand_id integer PRIMARY KEY,
	brand_name varchar(255) NOT NULL
);

CREATE TABLE products (
	product_id integer PRIMARY KEY,
	product_name varchar(255) NOT NULL,
	brand_id integer NOT NULL,
	category_id integer NOT NULL,
	model_year SMALLINT NOT NULL,
	list_price numeric(10,2) NOT NULL,
	FOREIGN KEY (category_id) REFERENCES categories (category_id),
	FOREIGN KEY (brand_id) REFERENCES brands (brand_id)
);

CREATE TABLE customers (
	customer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	phone varchar(25),
	email varchar(255) NOT NULL,
	street varchar(255),
	city varchar(50),
	state varchar(25),
	zip_code varchar(5)
);

CREATE TABLE stores (
	store_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	store_name varchar(255) NOT NULL,
	phone varchar(25),
	email varchar(255),
	street varchar(255),
	city varchar(255),
	state varchar(10),
	zip_code varchar(5)
);

CREATE TABLE staffs (
	staff_id integer PRIMARY KEY,
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	email varchar(255) NOT NULL UNIQUE,
	phone varchar(25),
	active smallint NOT NULL,
	store_id integer NOT NULL,
	manager_id integer,
	FOREIGN KEY (store_id) REFERENCES stores (store_id),
	FOREIGN KEY (manager_id) REFERENCES staffs (staff_id)
);

CREATE TABLE orders (
	order_id integer PRIMARY KEY,
	customer_id integer,
	order_status smallint NOT NULL,

	order_date DATE NOT NULL,
	required_date DATE NOT NULL,
	shipped_date DATE,
	store_id integer NOT NULL,
	staff_id integer NOT NULL,
	FOREIGN KEY (customer_id) REFERENCES customers (customer_id),
	FOREIGN KEY (store_id) REFERENCES stores (store_id),
	FOREIGN KEY (staff_id) REFERENCES staffs (staff_id)
);

CREATE TABLE order_items (
	order_id integer,
	item_id integer,
	product_id integer NOT NULL,
	quantity integer NOT NULL,
	list_price numeric(10,2) NOT NULL,
	discount numeric(4,2) NOT NULL DEFAULT 0,
	PRIMARY KEY (order_id, item_id),
	FOREIGN KEY (order_id) REFERENCES orders (order_id),
	FOREIGN KEY (product_id) REFERENCES products (product_id)
);

CREATE TABLE stocks (
	store_id integer,
	product_id integer,
	quantity integer,
	PRIMARY KEY (store_id, product_id),
	FOREIGN KEY (store_id) REFERENCES stores (store_id),
	FOREIGN KEY (product_id) REFERENCES products (product_id)
);
