#!/usr/bin/env python3
"""Study-overview (fig0_overview.pdf) and plan-vs-emit (fig0b_arms.pdf) diagrams for the EMSE version.
Numbers on the arrows come from E1_cells.csv medians (3,472 / 90,340 tokens; 1 call / 14-45 calls)
and the subject table (5 schemas; 54 + 202 renames; 172 requirements; 4 services; 293 mutants)."""
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

plt.rcParams.update({"font.size": 8, "font.family": "DejaVu Sans"})
INK, GREY, FILL, FILL2, FILL3 = "#222222", "#777777", "#f2f2f2", "#dfe8f0", "#f6e7d8"

def box(ax, x, y, w, h, text, fc=FILL, ec=INK, fs=8, bold=False, lw=0.8):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.01,rounding_size=0.12", fc=fc, ec=ec, lw=lw))
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=fs, color=INK,
            fontweight="bold" if bold else "normal", linespacing=1.25)

def arrow(ax, x0, y0, x1, y1, text=None, ls="-", tx=0, ty=0.12, fs=7, color=INK):
    ax.add_patch(FancyArrowPatch((x0, y0), (x1, y1), arrowstyle="-|>", mutation_scale=9, lw=0.8, color=color, linestyle=ls,
                                 shrinkA=1, shrinkB=1))
    if text: ax.text((x0 + x1) / 2 + tx, (y0 + y1) / 2 + ty, text, ha="center", va="center", fontsize=fs, color=GREY)

# ------------------------------------------------------------------ Fig: study overview
fig, ax = plt.subplots(figsize=(6.4, 5.2))
ax.set_xlim(0, 12); ax.set_ylim(0, 9.4); ax.axis("off")
F = 6.2
for y, lab in ((8.95, "E1   fidelity, validity, cost (RQ1, RQ2, RQ4)"), (5.55, "E1b   renamed-schema control (RQ1)"), (2.45, "E2   provisioned data downstream (RQ3, RQ4)")):
    ax.text(0.1, y, lab, fontsize=8, fontweight="bold", color=INK, va="center")
ax.axhline(5.95, color=GREY, lw=0.4, ls=":"); ax.axhline(2.85, color=GREY, lw=0.4, ls=":")

# E1 lane (y 6.3 .. 8.6)
box(ax, 0.1, 6.45, 2.4, 1.95, "5 public schemas\nChinook, Northwind,\nPagila, employees,\nDell DVD Store 2\n\nDDL + business case\n+ row targets", fc=FILL2, fs=F)
box(ax, 3.1, 7.55, 2.3, 0.7, "direct emission\nLLM writes rows", fc=FILL3, fs=F)
box(ax, 3.1, 6.7, 2.3, 0.7, "plan-then-execute\nLLM plan, engine writes rows", fc=FILL3, fs=5.8)
box(ax, 5.8, 7.55, 1.7, 0.7, "auto\n(engine, no LLM)", fs=F)
box(ax, 5.8, 6.7, 1.7, 0.7, "Faker", fs=F)
box(ax, 7.75, 6.7, 1.25, 1.55, "human\nfixtures\n(shipped)", fc=FILL2, fs=F)
box(ax, 9.3, 7.55, 2.6, 0.7, "validity: PostgreSQL\nrow-by-row load rate", fs=F)
box(ax, 9.3, 6.7, 2.6, 0.7, "fidelity: JS, KS, coverage\ncopy rate vs fixtures", fs=F)
for y in (7.9, 7.05):
    arrow(ax, 2.5, y, 3.1, y); arrow(ax, 5.4, y, 5.8, y); arrow(ax, 7.5, y, 9.3, y)
arrow(ax, 9.0, 7.05, 9.3, 7.05, color=GREY)
ax.text(6.0, 8.5, "2 providers (Claude Sonnet 4.6, GPT-4o) x 2 runs = 40 LLM cells; tokens and latency logged", fontsize=6.5, color=GREY, ha="center")

# E1b lane (y 3.2 .. 5.2)
box(ax, 0.1, 3.6, 2.4, 1.3, "same 5 schemas\n54 table + 202 column\nnames replaced\nby synonyms", fc=FILL2, fs=F)
box(ax, 3.1, 3.85, 2.3, 0.8, "direct emission and\nplan arms, one run", fc=FILL3, fs=F)
box(ax, 5.8, 3.85, 3.2, 0.8, "paired with the original cell\n(same schema, provider, arm)", fs=F)
box(ax, 9.3, 3.6, 2.6, 1.3, "fidelity: survives?\nvalidity: changes?\ncopying: survives?", fs=F)
arrow(ax, 2.5, 4.25, 3.1, 4.25); arrow(ax, 5.4, 4.25, 5.8, 4.25); arrow(ax, 9.0, 4.25, 9.3, 4.25)
arrow(ax, 1.3, 6.45, 1.3, 4.9, color=GREY, ls="--"); ax.text(1.45, 5.3, "deterministic\nrenamer", fontsize=6.3, color=GREY, va="center")

# E2 lane (y 0.4 .. 2.2)
box(ax, 0.1, 0.6, 2.4, 1.3, "4 open-source\nweb services\n172 requirements", fc=FILL2, fs=F)
box(ax, 3.1, 0.6, 2.3, 1.3, "fixture arms\nnone (G), functional,\nall profiles, human,\n+ state contract (E2c)", fc=FILL3, fs=F)
box(ax, 5.8, 0.85, 2.0, 0.8, "LLM test generator\n(frozen prompt)", fs=F)
box(ax, 8.1, 0.85, 1.0, 0.8, "generated\ntests", fs=F)
box(ax, 9.3, 0.6, 2.6, 1.3, "293 frozen mutants\nkills, usable yield\nMcNemar, Holm, CI", fs=F)
arrow(ax, 2.5, 1.25, 3.1, 1.25); arrow(ax, 5.4, 1.25, 5.8, 1.25); arrow(ax, 7.8, 1.25, 8.1, 1.25); arrow(ax, 9.1, 1.25, 9.3, 1.25)
arrow(ax, 4.25, 6.7, 4.25, 1.9, color=GREY, ls="--"); ax.text(4.4, 3.15, "run-1 plans re-executed on E2 DDLs", fontsize=6.3, color=GREY, va="center")
ax.text(6.0, 0.15, "Every input checksummed; every number regenerated by released scripts (Zenodo 10.5281/zenodo.22939052)", fontsize=6, color=GREY, ha="center")
fig.savefig("fig0_overview.pdf", bbox_inches="tight"); plt.close(fig)

# ------------------------------------------------------------------ Fig: plan-then-execute vs direct emission
fig, ax = plt.subplots(figsize=(6.4, 3.6))
ax.set_xlim(0, 12); ax.set_ylim(0, 6.6); ax.axis("off")
F = 6.2
ax.text(0.1, 6.35, "Direct emission", fontsize=8.5, fontweight="bold", color=INK, va="center")
ax.text(0.1, 2.95, "Plan-then-execute", fontsize=8.5, fontweight="bold", color=INK, va="center")
ax.axhline(3.3, color=GREY, lw=0.4, ls=":")

# direct (y 3.7 .. 6.0)
box(ax, 0.1, 4.2, 1.9, 1.5, "DDL\nbusiness case\nrow target", fc=FILL2, fs=F)
box(ax, 2.9, 4.2, 3.0, 1.5, "LLM writes the rows\n200 rows per call,\ntable by table, up to 60\nparent keys shown per FK", fc=FILL3, fs=F)
box(ax, 6.6, 4.2, 2.6, 1.5, "CSV rows\nevery key, uniqueness,\nNOT NULL and CHECK is\nthe model's to satisfy", fs=F)
box(ax, 9.9, 4.2, 2.0, 1.5, "PostgreSQL\nrow-by-row\nscorer", fc=FILL2, fs=F)
arrow(ax, 2.0, 4.95, 2.9, 4.95); arrow(ax, 5.9, 4.95, 6.6, 4.95); arrow(ax, 9.2, 4.95, 9.9, 4.95)
ax.text(4.4, 6.0, "14-45 calls per schema; median 90,340 tokens", fontsize=6.3, color=GREY, ha="center")
ax.text(4.4, 3.85, "misses: foreign keys, uniqueness, growing with schema difficulty", fontsize=6.3, color=GREY, ha="center")

# plan (y 0.3 .. 2.6)
box(ax, 0.1, 0.8, 1.9, 1.5, "DDL\nbusiness case\nrow target", fc=FILL2, fs=F)
box(ax, 2.9, 0.8, 1.9, 1.5, "LLM writes a\nYAML plan:\none generator\nper column", fc=FILL3, fs=F)
box(ax, 5.3, 0.8, 3.9, 1.5, "engine executes the plan (SynthData 1.2.2):\nFKs from keys that exist; uniqueness,\nCHECK, NOT NULL by construction;\nseed 42; the model never sees a row", fs=5.7)
box(ax, 9.9, 0.8, 2.0, 1.5, "PostgreSQL\nrow-by-row\nscorer", fc=FILL2, fs=F)
arrow(ax, 2.0, 1.55, 2.9, 1.55); arrow(ax, 4.8, 1.55, 5.3, 1.55); arrow(ax, 9.2, 1.55, 9.9, 1.55)
ax.text(3.85, 2.6, "1 call; median 3,472 tokens", fontsize=6.3, color=GREY, ha="center")
ax.text(5.5, 0.45, "misses: plan defects the engine mishandles (expr dates, self-references); the engine aborts rather than emitting invalid rows", fontsize=6.3, color=GREY, ha="center")
fig.savefig("fig0b_arms.pdf", bbox_inches="tight"); plt.close(fig)
print("ok")
