#!/usr/bin/env python3
"""Study overview for draft 4 (fig0_overview.pdf): four lanes, E1 / E1b / E1c / E2 (exploratory).
Helper code identical to make_diagrams.py; numbers from E1_cells.csv, E1c_copy_rate.csv and the subject table."""
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
plt.rcParams.update({"font.size": 8, "font.family": "DejaVu Sans"})
INK, GREY, FILL, FILL2, FILL3 = "#222222", "#777777", "#f2f2f2", "#dfe8f0", "#f6e7d8"
def box(ax, x, y, w, h, text, fc=FILL, ec=INK, fs=8, bold=False, lw=0.8):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.01,rounding_size=0.12", fc=fc, ec=ec, lw=lw))
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=fs, color=INK, fontweight="bold" if bold else "normal", linespacing=1.25)
def arrow(ax, x0, y0, x1, y1, ls="-", color=INK):
    ax.add_patch(FancyArrowPatch((x0, y0), (x1, y1), arrowstyle="-|>", mutation_scale=9, lw=0.8, color=color, linestyle=ls, shrinkA=1, shrinkB=1))

fig, ax = plt.subplots(figsize=(6.4, 6.6)); ax.set_xlim(0, 12); ax.set_ylim(0, 12.2); ax.axis("off"); F = 6.2
lanes = [(11.75, "E1   overlap with the fixtures, validity, cost (RQ1, RQ2)"), (8.35, "E1b   renamed-schema control (RQ1)"),
         (5.45, "E1c   copy rate across models and schemas (RQ1)"), (2.45, "E2   exploratory: provisioned data downstream (RQ3)")]
for y, lab in lanes: ax.text(0.1, y, lab, fontsize=8, fontweight="bold", color=INK, va="center")
for y in (8.75, 5.85, 2.85): ax.axhline(y, color=GREY, lw=0.4, ls=":")
# E1 lane (y 9.1 .. 11.4), shifted +2.8 from draft 3
d = 2.8
box(ax, 0.1, 6.45 + d, 2.4, 1.95, "5 public schemas\nChinook, Northwind,\nPagila, employees,\nDell DVD Store 2\n\nDDL + business case\n+ row targets", fc=FILL2, fs=F)
box(ax, 3.1, 7.55 + d, 2.3, 0.7, "direct emission\nLLM writes rows", fc=FILL3, fs=F)
box(ax, 3.1, 6.7 + d, 2.3, 0.7, "plan-then-execute\nLLM plan, engine writes rows", fc=FILL3, fs=5.8)
box(ax, 5.8, 7.55 + d, 1.7, 0.7, "auto\n(engine, no LLM)", fs=F)
box(ax, 5.8, 6.7 + d, 1.7, 0.7, "Faker", fs=F)
box(ax, 7.75, 6.7 + d, 1.25, 1.55, "human\nfixtures\n(shipped)", fc=FILL2, fs=F)
box(ax, 9.3, 7.55 + d, 2.6, 0.7, "validity: PostgreSQL\nrow-by-row load rate", fs=F)
box(ax, 9.3, 6.7 + d, 2.6, 0.7, "overlap: JS, KS, coverage\ncopy rate vs fixtures", fs=F)
for y in (7.9 + d, 7.05 + d):
    arrow(ax, 2.5, y, 3.1, y); arrow(ax, 5.4, y, 5.8, y); arrow(ax, 7.5, y, 9.3, y)
arrow(ax, 9.0, 7.05 + d, 9.3, 7.05 + d, color=GREY)
ax.text(6.0, 8.5 + d, "2 providers (Claude Sonnet 4.6, GPT-4o) x 2 runs = 40 LLM cells; tokens and latency logged", fontsize=6.5, color=GREY, ha="center")
# E1b lane (y 6.2 .. 8.0)
box(ax, 0.1, 3.6 + d, 2.4, 1.3, "same 5 schemas\n54 table + 202 column\nnames replaced\nby synonyms", fc=FILL2, fs=F)
box(ax, 3.1, 3.85 + d, 2.3, 0.8, "direct emission and\nplan arms, one run", fc=FILL3, fs=F)
box(ax, 5.8, 3.85 + d, 3.2, 0.8, "paired with the original cell\n(same schema, provider, arm)", fs=F)
box(ax, 9.3, 3.6 + d, 2.6, 1.3, "overlap: survives?\nvalidity: changes?\ncopying: survives?", fs=F)
arrow(ax, 2.5, 4.25 + d, 3.1, 4.25 + d); arrow(ax, 5.4, 4.25 + d, 5.8, 4.25 + d); arrow(ax, 9.0, 4.25 + d, 9.3, 4.25 + d)
arrow(ax, 1.3, 6.45 + d, 1.3, 4.9 + d, color=GREY, ls="--"); ax.text(1.45, 5.3 + d, "deterministic\nrenamer", fontsize=6.3, color=GREY, va="center")
# E1c lane (y 3.2 .. 5.2)
box(ax, 0.1, 3.5, 2.4, 1.5, "8 public schemas\nthe 5 above plus\nClassicModels,\nOracle HR, BikeStores", fc=FILL2, fs=5.9)
box(ax, 3.1, 3.65, 2.3, 1.2, "direct emission only\n5 models, one run\n(3 vendors, one\nopen-weight)", fc=FILL3, fs=5.9)
box(ax, 5.8, 3.75, 3.2, 1.0, "40 schema x model cells\n(10 from E1, 30 new)", fs=F)
box(ax, 9.3, 3.5, 2.6, 1.5, "copy rate vs shipped\nfixture; Oracle HR vs\nthree fixture editions", fs=F)
arrow(ax, 2.5, 4.25, 3.1, 4.25); arrow(ax, 5.4, 4.25, 5.8, 4.25); arrow(ax, 9.0, 4.25, 9.3, 4.25)
# E2 lane (y 0.4 .. 2.2)
box(ax, 0.1, 0.6, 2.4, 1.3, "4 open-source\nweb services\n172 requirements", fc=FILL2, fs=F)
box(ax, 3.1, 0.6, 2.3, 1.3, "fixture arms\nnone (G), functional,\nall profiles, human,\n+ state contract (E2c)", fc=FILL3, fs=F)
box(ax, 5.8, 0.85, 2.0, 0.8, "LLM test generator\n(frozen prompt)", fs=F)
box(ax, 8.1, 0.85, 1.0, 0.8, "generated\ntests", fs=F)
box(ax, 9.3, 0.6, 2.6, 1.3, "293 frozen mutants\nkills, usable yield\nMcNemar, Holm, CI", fs=F)
arrow(ax, 2.5, 1.25, 3.1, 1.25); arrow(ax, 5.4, 1.25, 5.8, 1.25); arrow(ax, 7.8, 1.25, 8.1, 1.25); arrow(ax, 9.1, 1.25, 9.3, 1.25)
ax.text(6.0, 0.15, "Every input checksummed; every number regenerated by released scripts (Zenodo; see Data availability)", fontsize=6, color=GREY, ha="center")
fig.savefig("fig0_overview.pdf", bbox_inches="tight"); fig.savefig("fig0_overview.png", dpi=200, bbox_inches="tight"); plt.close(fig)
print("ok")
